### ISSUE TITLE
Implement support for carto torque maps on map explorer / thematic maps

### ISSUE THREAD

**Issue by acorbi** [OpenDevelopmentMekong/wp-odm_theme#495]
Cartodb layers which uses the **torque** time-series visualization (see screenshot) cannot be enabled in the map explorer or thematic maps.

![screenshot from 2016-09-28 16-39-23](https://cloud.githubusercontent.com/assets/384894/18918143/22c865fc-859a-11e6-8620-c04263a866c1.png)

When selected on map explorer, javascript error appears.

![screenshot from 2016-09-28 16-39-08](https://cloud.githubusercontent.com/assets/384894/18918144/23e47f66-859a-11e6-8f48-dc88d21daf9c.png)

**Comment by acorbi** [comment]
Fixed via https://github.com/OpenDevelopmentMekong/jeo/commit/190d5f8dc0d7ad7e4f82214db152fdef36d383df

**Comment by prustar** [comment]
https://opendevelopmentmekong.net/maps/fire/#!/story=post-2921635&loc=13.346865014577924,105.413818359375,6&full=true

Still not working as expected. 
I uploaded the combined dataset for all countries into Carto but it's not handling the data very well there's also a CSS error in line 4 - Torque frame count - I tried a few different values but nothing seemed to make it work? If we could get this to work it would be better as then we wouldn't need to toggle individual country layers but the whole region at once, meaning only one control. 
 
https://odm.carto.com/viz/3befa46c-bfe4-41af-8d8c-0c819f45156a/map

**Comment by acorbi** [comment]
@prustar I have adapted the layers **Test VIIRS_carto** on PP and added the link to the carto map with the regional scope. It is working fine, without errors, see:

https://pp.opendevelopmentmekong.net/map-explorer

Im closing this issue, please re-open if you can still re-produce
